'use strict'

const WEATHER_ICON = {
  RAIN_THUNDER: 'rainThunder',
  RAINY: 'rainy',
  SNOWY: 'snowy',
  SUNNY: 'sunny',
  PARTLY_CLOUDY: 'partlyCloudy',
  CLOUDY: 'cloudy'
}

const ICON_MAP = {
  '01d': WEATHER_ICON.SUNNY,
  '01n': WEATHER_ICON.SUNNY,
  '02d': WEATHER_ICON.PARTLY_CLOUDY,
  '02n': WEATHER_ICON.PARTLY_CLOUDY,
  '03d': WEATHER_ICON.CLOUDY,
  '03n': WEATHER_ICON.CLOUDY,
  '04d': WEATHER_ICON.CLOUDY,
  '04n': WEATHER_ICON.CLOUDY,
  '09d': WEATHER_ICON.RAINY,
  '09n': WEATHER_ICON.RAINY,
  '10d': WEATHER_ICON.RAINY,
  '10n': WEATHER_ICON.RAINY,
  '11d': WEATHER_ICON.RAIN_THUNDER,
  '11n': WEATHER_ICON.RAIN_THUNDER,
  '13d': WEATHER_ICON.SNOWY,
  '13n': WEATHER_ICON.SNOWY,
  '50d': WEATHER_ICON.CLOUDY,
  '50n': WEATHER_ICON.CLOUDY
}

const DEFAULT_INTERVAL = 1800000

module.exports = {
  WEATHER_ICON,
  ICON_MAP,
  DEFAULT_INTERVAL
}
